✨ feat: add missing eslint config
Hemocione/hemocione-competitions pull request #3
Opened 2024-02-03 21:07 UTC by CarlosZoft

## Descrição

Adicionando configuração do lint, para evitar erros bobos no decorrer do desenvolvimento

2024-02-03 23:46 UTC, guim4dev requested changes

2024-02-03 23:46 UTC, guim4dev commented on components/CompetitionSummary.vue
> +      <img :style="{ height: '50px' }" src="/img/bodylessArrow.svg">
o linter tirou o closing da tag

2024-02-03 23:46 UTC, guim4dev commented on components/CompetitionSummary.vue
> -      <br />
o linter tirou o closing das tags (deveriamos estar usando BRs aqui ?)

2024-02-04 16:03 UTC, CarlosZoft commented on components/CompetitionSummary.vue
> +      <img :style="{ height: '50px' }" src="/img/bodylessArrow.svg">
@guim4dev, eh que essas tags não tem sub-elementos bonitão

2024-02-04 16:04 UTC, CarlosZoft commented on components/CompetitionSummary.vue
> -      <br />
@guim4dev, não, vou resolver isso em outros mrs

2024-02-06 21:39 UTC, guim4dev approved these changes

2024-02-06 21:39 UTC, merged